# -*- coding: utf-8 -*-
"""Week4GenAIBreakoutAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3ctLmz_J9wrjx-yQJa8tr_zedUuk4E7
"""

pip install happytransformer

from happytransformer import HappyTextToText, TTSettings

happy_tt = HappyTextToText("T5", "vennify/t5-base-grammar-correction")

args = TTSettings(num_beams=5, min_length=1)

# Add the prefix "grammar: " before each input
result = happy_tt.generate_text("grammar: This sentences has has bads grammar.", args=args)

print(result.text) # This sentence has bad grammar.

# Add the prefix "grammar: " before each input
result = happy_tt.generate_text("grammar: When I grow up, I start to understand what he said is quite right.", args=args)

print(result.text)